name: Project Automation

permissions:
  issues: write
  pull-requests: write
  repository-projects: write
  
on:
  issues:
    types: [opened, assigned, closed, reopened]
  pull_request:
    types: [opened, closed, review_requested]

jobs:
  project_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/JJOK97/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}
      
      - name: Move to column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: AntBot
          column: Todo
          repo-token: ${{ secrets.PROJECT_TOKEN }}
